// flow-typed signature: 7175ff6db61a7bcb8d11cf510e2e8f8e
// flow-typed version: <<STUB>>/better-sqlite3_v^4.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'better-sqlite3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'better-sqlite3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'better-sqlite3/benchmark/factory' {
  declare module.exports: any;
}

declare module 'better-sqlite3/benchmark/implementations' {
  declare module.exports: any;
}

declare module 'better-sqlite3/benchmark/index' {
  declare module.exports: any;
}

declare module 'better-sqlite3/benchmark/runner' {
  declare module.exports: any;
}

declare module 'better-sqlite3/benchmark/trials' {
  declare module.exports: any;
}

declare module 'better-sqlite3/benchmark/types/insert' {
  declare module.exports: any;
}

declare module 'better-sqlite3/benchmark/types/real-world' {
  declare module.exports: any;
}

declare module 'better-sqlite3/benchmark/types/select-all' {
  declare module.exports: any;
}

declare module 'better-sqlite3/benchmark/types/select-iterate' {
  declare module.exports: any;
}

declare module 'better-sqlite3/benchmark/types/select' {
  declare module.exports: any;
}

declare module 'better-sqlite3/benchmark/types/transaction' {
  declare module.exports: any;
}

declare module 'better-sqlite3/deps/install' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/database' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/pragma' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/register' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/sqlite-error' {
  declare module.exports: any;
}

declare module 'better-sqlite3/lib/util' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/00.sqlite-error' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/10.database.open' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/11.database.close' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/12.database.pragma' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/13.database.prepare' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/14.database.transaction' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/15.database.exec' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/20.statement.run' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/21.statement.get' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/22.statement.all' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/23.statement.iterate' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/24.statement.bind' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/30.transaction.run' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/31.transaction.bind' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/40.database.checkpoint' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/41.database.close' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/42.database.register' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/43.database.load-extension' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/50.integers' {
  declare module.exports: any;
}

declare module 'better-sqlite3/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'better-sqlite3/benchmark/factory.js' {
  declare module.exports: $Exports<'better-sqlite3/benchmark/factory'>;
}
declare module 'better-sqlite3/benchmark/implementations.js' {
  declare module.exports: $Exports<'better-sqlite3/benchmark/implementations'>;
}
declare module 'better-sqlite3/benchmark/index.js' {
  declare module.exports: $Exports<'better-sqlite3/benchmark/index'>;
}
declare module 'better-sqlite3/benchmark/runner.js' {
  declare module.exports: $Exports<'better-sqlite3/benchmark/runner'>;
}
declare module 'better-sqlite3/benchmark/trials.js' {
  declare module.exports: $Exports<'better-sqlite3/benchmark/trials'>;
}
declare module 'better-sqlite3/benchmark/types/insert.js' {
  declare module.exports: $Exports<'better-sqlite3/benchmark/types/insert'>;
}
declare module 'better-sqlite3/benchmark/types/real-world.js' {
  declare module.exports: $Exports<'better-sqlite3/benchmark/types/real-world'>;
}
declare module 'better-sqlite3/benchmark/types/select-all.js' {
  declare module.exports: $Exports<'better-sqlite3/benchmark/types/select-all'>;
}
declare module 'better-sqlite3/benchmark/types/select-iterate.js' {
  declare module.exports: $Exports<'better-sqlite3/benchmark/types/select-iterate'>;
}
declare module 'better-sqlite3/benchmark/types/select.js' {
  declare module.exports: $Exports<'better-sqlite3/benchmark/types/select'>;
}
declare module 'better-sqlite3/benchmark/types/transaction.js' {
  declare module.exports: $Exports<'better-sqlite3/benchmark/types/transaction'>;
}
declare module 'better-sqlite3/deps/install.js' {
  declare module.exports: $Exports<'better-sqlite3/deps/install'>;
}
declare module 'better-sqlite3/index' {
  declare module.exports: $Exports<'better-sqlite3'>;
}
declare module 'better-sqlite3/index.js' {
  declare module.exports: $Exports<'better-sqlite3'>;
}
declare module 'better-sqlite3/lib/database.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/database'>;
}
declare module 'better-sqlite3/lib/pragma.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/pragma'>;
}
declare module 'better-sqlite3/lib/register.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/register'>;
}
declare module 'better-sqlite3/lib/sqlite-error.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/sqlite-error'>;
}
declare module 'better-sqlite3/lib/util.js' {
  declare module.exports: $Exports<'better-sqlite3/lib/util'>;
}
declare module 'better-sqlite3/test/00.sqlite-error.js' {
  declare module.exports: $Exports<'better-sqlite3/test/00.sqlite-error'>;
}
declare module 'better-sqlite3/test/10.database.open.js' {
  declare module.exports: $Exports<'better-sqlite3/test/10.database.open'>;
}
declare module 'better-sqlite3/test/11.database.close.js' {
  declare module.exports: $Exports<'better-sqlite3/test/11.database.close'>;
}
declare module 'better-sqlite3/test/12.database.pragma.js' {
  declare module.exports: $Exports<'better-sqlite3/test/12.database.pragma'>;
}
declare module 'better-sqlite3/test/13.database.prepare.js' {
  declare module.exports: $Exports<'better-sqlite3/test/13.database.prepare'>;
}
declare module 'better-sqlite3/test/14.database.transaction.js' {
  declare module.exports: $Exports<'better-sqlite3/test/14.database.transaction'>;
}
declare module 'better-sqlite3/test/15.database.exec.js' {
  declare module.exports: $Exports<'better-sqlite3/test/15.database.exec'>;
}
declare module 'better-sqlite3/test/20.statement.run.js' {
  declare module.exports: $Exports<'better-sqlite3/test/20.statement.run'>;
}
declare module 'better-sqlite3/test/21.statement.get.js' {
  declare module.exports: $Exports<'better-sqlite3/test/21.statement.get'>;
}
declare module 'better-sqlite3/test/22.statement.all.js' {
  declare module.exports: $Exports<'better-sqlite3/test/22.statement.all'>;
}
declare module 'better-sqlite3/test/23.statement.iterate.js' {
  declare module.exports: $Exports<'better-sqlite3/test/23.statement.iterate'>;
}
declare module 'better-sqlite3/test/24.statement.bind.js' {
  declare module.exports: $Exports<'better-sqlite3/test/24.statement.bind'>;
}
declare module 'better-sqlite3/test/30.transaction.run.js' {
  declare module.exports: $Exports<'better-sqlite3/test/30.transaction.run'>;
}
declare module 'better-sqlite3/test/31.transaction.bind.js' {
  declare module.exports: $Exports<'better-sqlite3/test/31.transaction.bind'>;
}
declare module 'better-sqlite3/test/40.database.checkpoint.js' {
  declare module.exports: $Exports<'better-sqlite3/test/40.database.checkpoint'>;
}
declare module 'better-sqlite3/test/41.database.close.js' {
  declare module.exports: $Exports<'better-sqlite3/test/41.database.close'>;
}
declare module 'better-sqlite3/test/42.database.register.js' {
  declare module.exports: $Exports<'better-sqlite3/test/42.database.register'>;
}
declare module 'better-sqlite3/test/43.database.load-extension.js' {
  declare module.exports: $Exports<'better-sqlite3/test/43.database.load-extension'>;
}
declare module 'better-sqlite3/test/50.integers.js' {
  declare module.exports: $Exports<'better-sqlite3/test/50.integers'>;
}
declare module 'better-sqlite3/test/util.js' {
  declare module.exports: $Exports<'better-sqlite3/test/util'>;
}
