/**
 * @license
 * Copyright (C) Pryv https://pryv.com
 * This file is part of Pryv.io and released under BSD-Clause-3 License
 * Refer to LICENSE file
 */
// flow-typed signature: 80e7b3fc8c0f31be76a2ea8c57e29f8f
// flow-typed version: <<STUB>>/sqlite_v^2.9.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sqlite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sqlite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sqlite/legacy' {
  declare module.exports: any;
}

declare module 'sqlite/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sqlite/legacy.js' {
  declare module.exports: $Exports<'sqlite/legacy'>;
}
declare module 'sqlite/main.js' {
  declare module.exports: $Exports<'sqlite/main'>;
}
